on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Create openssl Release

jobs:
  build:
    name: compile openssl then deploy
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: One Step
      run: .github/workflows/onestep.sh openssl all